import{s as F,a as g,i as c}from"./assets/vendor-c817b881.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const d="/goit-js-hw-12/assets/bi_x-octagon-ae8a7ac1.svg",p=document.querySelector(".form"),f=document.querySelector(".form-input"),h=document.querySelector(".gallery"),s=document.createElement("div");s.classList.add("loader");const v=new F("li a",{captionsData:"alt",captionClass:"img-caption",captionDelay:250}),m=document.querySelector(".load-more-btn");let l=1,y="41929636-e94244ac3daa63b74aaebcf18",u="";p.addEventListener("submit",L);m.addEventListener("click",w);function b(r){const o=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:t,views:n,comments:A,downloads:x})=>`
                <li class="gallery-item">
                    <a class="item-link" href="${i}">
                        <img
                            src="${a}"
                            alt="${e}"
                            width="360"
                            height="200"
                        />
                    </a>
                    <ul class="mini-list">
                        <!-- (existing code for mini-list) -->
                    </ul>
                </li>`).join("");s.remove(),h.insertAdjacentHTML("beforeend",o),r.length<30?(m.style.display="none",l===1?c.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"#EF4040",messageColor:"#FAFAFB",iconUrl:d}):c.show({message:"We are sorry, but you have reached the end of search results.",position:"topRight",color:"#EF4040",messageColor:"#FAFAFB",iconUrl:d})):m.style.display="block",v.refresh()}async function L(r){r.preventDefault(),h.innerHTML="",p.after(s),u=f.value,l=1;try{const o=await g.get("https://pixabay.com/api/",{params:{key:y,q:u,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:30}}),{hits:a}=o.data;b(a)}catch(o){s.remove(),c.show({message:`${o}`,position:"topRight",color:"#EF4040",messageColor:"#FAFAFB",iconUrl:"/img/bi_x-octagon.svg"})}}async function w(){f.value="",p.after(s);try{l++;const r=await g.get("https://pixabay.com/api/",{params:{key:y,q:u,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:30,page:l}}),{hits:o}=r.data;b(o)}catch(r){s.remove(),c.show({message:`${r}`,position:"topRight",color:"#EF4040",messageColor:"#FAFAFB",iconUrl:"/img/bi_x-octagon.svg"})}}
//# sourceMappingURL=commonHelpers.js.map
